[deps]
BayesBase = "b4ee3484-f114-42fe-b91c-797d54a0c67e"
DeltaMessagePassingRules = "ea5de7a7-24c9-4a61-90ce-ef77c844b13f"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ExponentialFamily = "62312e5e-252a-4322-ace9-a5f4bf9b357b"
GCVMessagePassingRules = "2bb838d1-ae36-49a2-8c64-82a0acccfa93"
GaussianCouplingMessagePassingRules = "a57ce80c-d854-4eb3-973d-f0d0550df039"
MessagePassingRulesApproximations = "36043009-14b3-4068-9fb9-f1e492c92d7d"
MessagePassingRulesBase = "4a5b64c7-30c9-4471-82f2-bbe8464b157d"
MessagePassingRulesTestUtils = "08c5795c-a039-451c-8c5c-d65dcf644a97"
ProbitMessagePassingRules = "1bb8e9a6-2578-4a1e-b3eb-7f663b479540"
ReactiveMP = "a194aa59-28ba-4574-a09c-4a745416d6e3"
RxInfer = "86711068-29c9-4ff7-b620-ae75d7495b3d"
StandardMessagePassingRules = "d166223a-7879-43b1-add3-64af0a178e9e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
DeltaMessagePassingRules = {path = "../../lib/DeltaMessagePassingRules"}
GCVMessagePassingRules = {path = "../../lib/GCVMessagePassingRules"}
GaussianCouplingMessagePassingRules = {path = "../../lib/GaussianCouplingMessagePassingRules"}
MessagePassingRulesApproximations = {path = "../../lib/MessagePassingRulesApproximations"}
MessagePassingRulesBase = {path = "../../lib/MessagePassingRulesBase"}
MessagePassingRulesTestUtils = {path = "../../lib/MessagePassingRulesTestUtils"}
ProbitMessagePassingRules = {path = "../../lib/ProbitMessagePassingRules"}
StandardMessagePassingRules = {path = "../../lib/StandardMessagePassingRules"}

[compat]
ReactiveMP = "=6.5.0"
RxInfer = "=5.5.2"
julia = "1.10"
