# A list of nodes predefined in the package
# Stochastic nodes
include("predefined/uninformative.jl")
include("predefined/uniform.jl")
include("predefined/normal_mean_variance.jl")
include("predefined/normal_mean_precision.jl")
include("predefined/mv_normal_mean_covariance.jl")
include("predefined/mv_normal_mean_precision.jl")
include("predefined/mv_normal_mean_scale_precision.jl")
include("predefined/mv_normal_weighted_mean_precision.jl")
include("predefined/gamma.jl")
include("predefined/gamma_inverse.jl")
include("predefined/gamma_shape_rate.jl")
include("predefined/beta.jl")
include("predefined/categorical.jl")
include("predefined/matrix_dirichlet.jl")
include("predefined/dirichlet.jl")
include("predefined/bernoulli.jl")
include("predefined/gcv.jl")
include("predefined/wishart.jl")
include("predefined/wishart_inverse.jl")
include("predefined/normal_mixture.jl")
include("predefined/gamma_mixture.jl")
include("predefined/dot_product.jl")
include("predefined/softdot.jl")
include("predefined/transition.jl")
include("predefined/autoregressive.jl")
include("predefined/bifm.jl")
include("predefined/bifm_helper.jl")
include("predefined/probit.jl")
include("predefined/poisson.jl")
include("predefined/continuous_transition.jl")
include("predefined/half_normal.jl")

include("predefined/flow/flow.jl")
include("predefined/delta/delta.jl")
include("predefined/distribution/distribution.jl")

# Deterministic nodes
include("predefined/addition.jl")
include("predefined/subtraction.jl")
include("predefined/multiplication.jl")
include("predefined/and.jl")
include("predefined/or.jl")
include("predefined/not.jl")
include("predefined/implication.jl")
include("predefined/mixture.jl")
