name: CI
on:
  pull_request:
  push:
  schedule:
    - cron: '44 9 16 * *' # run the cron job one time per month
jobs:
  format: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1         
        with:
          version: '1.7'
      - run: julia -e 'import Pkg; Pkg.add("JuliaFormatter"); import JuliaFormatter; if JuliaFormatter.format("src", overwrite = false, verbose = true) exit(0) else exit(1) end'
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    needs: format
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - '1.7'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        env:
          PYTHON: ""
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@latest
        env:
            PYTHON: ""
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
      - name: Archive test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: test/_output
  benchmark:
    name: Benchmarks
    runs-on: ubuntu-latest
    needs: test
    env: 
      working-directory: './benchmark'
    if: contains(github.event.head_commit.message, '[benchmark]')
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.7'
      - run: julia --project=. -e 'using Pkg; Pkg.instantiate()'
        working-directory: ${{ env.working-directory }}
      - run: julia --project=. -e 'using PkgBenchmark; using BenchmarkCI; BenchmarkCI.judge(target = PkgBenchmark.BenchmarkConfig(; id = nothing, juliacmd = `julia -O3`), pkgdir = "$(pwd())/../")'
        working-directory: ${{ env.working-directory }}
      - run: julia --project=. -e 'using PkgBenchmark; using BenchmarkCI; BenchmarkCI.displayjudgement()'
        working-directory: ${{ env.working-directory }}
      - run: julia --project=. -e 'using Base64; using BenchmarkCI; BenchmarkCI.pushresult(; url = "git@github.com:biaslab/ReactiveMP.jl.git", title = "Benchmark result (via Travis)", branch = "gh-benchmarks", sshkey = String(Base64.base64decode(ENV["BENCHMARK_KEY"]))); '
        working-directory: ${{ env.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BENCHMARK_KEY: ${{ secrets.BENCHMARK_KEY }}
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
      - uses: julia-actions/julia-buildpkg@latest          
        with:
          version: '1.7'
      - run: |
          julia --project=docs -e '
            ENV["PYTHON"]=""
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            Pkg.build("PyPlot")'
      - run: julia --project=docs docs/make.jl
        env:
          PYTHON: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}